name: CI
on:
  push:
    branches:
      - generate-source
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: generate-source
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: Setup hexo
        env:
          GITHUB_TOKEN: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          git config --global user.email "tanxinzheng@139.com"
          git config --global user.name "tanxinzheng"
          npm install hexo-cli -g
          npm install
      - name: Hexo deploy
        run: |
          hexo clean
          hexo d