name: CI
on:
  push:
    branches:
      - generate-source
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: generate-source
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: Build and Deploy hexo
        uses: JamesIves/github-pages-deploy-action@master
        run:|
          git config --global user.email "tanxinzheng@139.com"
          git config --global user.name "tanxinzheng"
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: generate-source
          BRANCH: master
          FOLDER: public
          BUILD_SCRIPT: npm i -g hexo && npm install && hexo generate