name: CI
on:
  push:
    branches:
      - generate-source
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: generate-source
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: Setup hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "tanxinzheng@139.com"
          git config --global user.name "tanxinzheng"
          npm install hexo-cli -g
          npm install
      - name: Hexo deploy To Github page
        run: |
          hexo clean
          # 此处hexo generate换成使用gulp对静态资源进行压缩
          gulp build
          hexo deploy
      - uses: manyuanrong/setup-ossutil@v1.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
           # endpoint 可以去oss控制台上查看
           endpoint: "oss-cn-shanghai.aliyuncs.com"
           # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
           access-key-id: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_ID }}
           access-key-secret: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_SECRET }}
      - name: Deploy To OSS
        run: ossutil cp public oss://txz-blog/ -rf